FROM traefik:v3.1

# https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
COPY traefik/traefik-dynamic-configuration.yaml /etc/traefik/dynamic/traefik-dynamic-configuration.yaml
