ARG TRAEFIK_VERSION=latest
FROM traefik:${TRAEFIK_VERSION}

# https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
COPY traefik/traefik-dynamic-configuration.yaml /etc/traefik/dynamic/traefik-dynamic-configuration.yaml
