site_name: Colabkit Portal

# ページとmarkdownファイルを紐づける設定
nav:
  - TOP: index.md
  - ユーザーガイド: ユーザーガイド.md
  - セットアップガイド: セットアップガイド.md
  - 管理者ガイド: 管理者ガイド.md

# ページのデザイン設定
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra:
  # 検索機能の設定
  search:
    language: 'jp'
  # 環境変数
  HOST_IP: !ENV 'HOST_IP'
  PORTAL_HTTP_PORT: !ENV 'PORTAL_HTTP_PORT'
  PORTAL_HTTPS_PORT: !ENV 'PORTAL_HTTPS_PORT'
  GITLAB_PORT: !ENV 'GITLAB_PORT'
  GITLAB_MATTERMOST_PORT: !ENV 'GITLAB_MATTERMOST_PORT'
  GITLAB_PAGES_PORT: !ENV 'GITLAB_PAGES_PORT'
  GITLAB_REGISTRY_PORT: !ENV 'GITLAB_REGISTRY_PORT'
  GROWI_PORT: !ENV 'GROWI_PORT'
  PLANTUML_PORT: !ENV 'PLANTUML_PORT'
  LLDAP_WEB_PORT: !ENV 'LLDAP_WEB_PORT'
  TRAEFIK_DASHBOARD_PORT: !ENV 'TRAEFIK_DASHBOARD_PORT'

# 拡張機能の設定
plugins:
    - search
    - macros
