site_name: Colabkit Portal

# ページとmarkdownファイルを紐づける設定
nav:
  - TOP: index.md
  - ユーザーガイド: ユーザーガイド.md
  - セットアップガイド: セットアップガイド.md
  - 管理者ガイド: 管理者ガイド.md

# ページのデザイン設定
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra:
  # 検索機能の設定
  search:
    language: 'jp'

# 拡張機能の設定
plugins:
    - search
    - macros:
        module_name: mkdocs-module
        on_undefined: strict
        on_error_fail: true
